name: Deploy Server to EC2

on:
  push:
    branches:
      - master
    paths:
      - 'AutoEmply/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AutoEmply
            git pull
            pkill -f "dotnet run" || true
            sudo fuser -k 5003/tcp || true
            cd AutoEmply
            ASPNETCORE_ENVIRONMENT=Production nohup dotnet run --no-launch-profile &